### ISSUE TITLE
Analyzer not working with version 7.0.0

### ISSUE THREAD

**Issue by tariquememon** [RemcoBlok/MassTransit.Analyzers#3]
I've installed MassTransit.Analyzers (v7.0.0) to work with MassTransit (v7.0.0) but it is not providing any suggestions. I am following Chris' tutorial on youtube and was expecting a green squiggly to appear next to the new keyword.

![image](https://user-images.githubusercontent.com/8287104/87405242-bc96a180-c5f1-11ea-9e46-a020ecf115fc.png)

**Comment by RemcoBlok** [comment]
Hi, you've reached the repo where the MassTransit analyzer was initially developed, but it has since moved to https://github.com/MassTransit/MassTransit. Can you raise your issue there?
